### ISSUE TITLE
Action is not working

### ISSUE THREAD

**Issue by defi-bear** [orta/nightly-profile-updater#1]
Hello @orta 
First of all, thank you for creating a great repo.
I've forked your repo and it's working but the action is not working for me and it's not updating as in real-time.
Is there anything that I should configure?
https://github.com/Shing-Ho/nightly-profile-updater
How can I set `GITHUB_API_TOKEN: ${{ secrets.GIST_GITHUB_API_TOKEN }}`?
Thank you.

**Comment by orta** [comment]
There's a security section in the repo settings for that
